import type { AnsweringPlanDocument } from "@/domain/answering-plan/schema";

type DaySchedule = AnsweringPlanDocument["hoursAvailability"]["regularHours"]["monday"];

export function emptyWeeklySchedule() {
  const closedDay = (): DaySchedule => ({ open: false, periods: [], note: null });
  return {
    monday: closedDay(),
    tuesday: closedDay(),
    wednesday: closedDay(),
    thursday: closedDay(),
    friday: closedDay(),
    saturday: closedDay(),
    sunday: closedDay(),
  };
}

export function createDefaultAnsweringPlanDocument(): AnsweringPlanDocument {
  const defaultIntakeFieldIds = ["field_name", "field_phone", "field_email", "field_details"];

  return {
    schemaVersion: "1.0.0",
    businessProfile: {
      businessName: null,
      legalName: null,
      websiteUrl: null,
      businessType: {
        label: null,
        description: null,
        aliases: [],
      },
      description: null,
      timezone: null,
      primaryLanguage: "en",
      additionalLanguages: [],
      publicContact: {
        phone: null,
        email: null,
        contactUrl: null,
      },
      address: {
        line1: null,
        line2: null,
        city: null,
        region: null,
        postalCode: null,
        country: null,
      },
      businessNamePronunciation: null,
    },
    temporaryUpdates: [],
    offerings: [],
    hoursAvailability: {
      enabled: false,
      timezone: null,
      regularHours: emptyWeeklySchedule(),
      specialDates: [],
      afterHours: {
        enabled: true,
        mode: "take_message",
        instructions: "Collect the caller's details and reason for calling.",
        callerWording: "The team is unavailable right now, but I can take a message for them.",
        routingRuleId: null,
      },
      availabilityNotes: null,
    },
    locationsCoverage: {
      enabled: false,
      mode: "not_applicable",
      locations: [],
      serviceAreas: [],
      callerFacingDescription: null,
    },
    knowledgeItems: [],
    requestTypes: [
      {
        id: "request_general",
        enabled: true,
        name: "General request",
        singularLabel: "Request",
        pluralLabel: "Requests",
        description: "A caller request or callback for the business team.",
        intakeFieldIds: defaultIntakeFieldIds,
        completionMode: "create_request",
        defaultAssigneeContactIds: [],
        confirmationWording: "I have captured your request for the team.",
        statuses: ["requested", "in_progress", "completed"],
      },
    ],
    intakeFields: [
      {
        id: "field_name",
        enabled: true,
        label: "Name",
        key: "name",
        type: "text",
        required: true,
        options: [],
        spokenPrompt: "May I have your name?",
        validationInstructions: null,
        askWhen: { mode: "always", requestTypeIds: [], offeringIds: [], scenarioIds: [], customCondition: null },
        order: 1,
      },
      {
        id: "field_phone",
        enabled: true,
        label: "Phone",
        key: "phone",
        type: "phone",
        required: true,
        options: [],
        spokenPrompt: "What is the best phone number to reach you?",
        validationInstructions: "Read the number back once for confirmation.",
        askWhen: { mode: "always", requestTypeIds: [], offeringIds: [], scenarioIds: [], customCondition: null },
        order: 2,
      },
      {
        id: "field_email",
        enabled: true,
        label: "Email",
        key: "email",
        type: "email",
        required: false,
        options: [],
        spokenPrompt: "What email address should the team use?",
        validationInstructions: null,
        askWhen: { mode: "always", requestTypeIds: [], offeringIds: [], scenarioIds: [], customCondition: null },
        order: 3,
      },
      {
        id: "field_details",
        enabled: true,
        label: "Reason for calling",
        key: "details",
        type: "multiline_text",
        required: true,
        options: [],
        spokenPrompt: "What would you like the team to know?",
        validationInstructions: null,
        askWhen: { mode: "always", requestTypeIds: [], offeringIds: [], scenarioIds: [], customCondition: null },
        order: 4,
      },
    ],
    booking: {
      enabled: false,
      defaultMethod: "none",
      bookingLinkId: null,
      integrationConnectionId: null,
      defaultIntakeFieldIds: defaultIntakeFieldIds,
      confirmationWording: null,
      unavailableBehavior: {
        mode: "take_message",
        wording: "I can take your details and have the team follow up.",
      },
      offeringOverrides: [],
    },
    scenarios: [
      {
        id: "scenario_information",
        enabled: true,
        name: "Business information question",
        description: "A caller asks about approved business information.",
        whenCaller: "The caller asks about offerings, hours, location, coverage, or an approved FAQ or policy.",
        exampleCallerPhrases: ["What do you offer?", "When are you open?"],
        priority: 10,
        appliesWhen: { timeMode: "any", locationIds: [], offeringIds: [], customCondition: null },
        actions: [{ type: "answer_approved_information", knowledgeItemIds: [] }],
        collectFieldIds: [],
        requestTypeId: null,
        notifyRecipientIds: [],
        fallback: { mode: "unknown_handling", instruction: null, routingRuleId: null },
        callerWording: null,
      },
      {
        id: "scenario_request",
        enabled: true,
        name: "Request or callback",
        description: "A caller wants help from the business or asks someone to follow up.",
        whenCaller: "The caller wants a request, appointment, quote, booking, callback, or message handled by the business.",
        exampleCallerPhrases: ["Can someone call me back?", "I would like to make a request."],
        priority: 20,
        appliesWhen: { timeMode: "any", locationIds: [], offeringIds: [], customCondition: null },
        actions: [
          { type: "collect_information", intakeFieldIds: ["field_name", "field_phone", "field_details"] },
          { type: "create_request", requestTypeId: "request_general" },
        ],
        collectFieldIds: ["field_name", "field_phone", "field_details"],
        requestTypeId: "request_general",
        notifyRecipientIds: [],
        fallback: { mode: "take_message", instruction: null, routingRuleId: null },
        callerWording: "I can capture your details for the team.",
      },
      {
        id: "scenario_message",
        enabled: true,
        name: "Message",
        description: "A caller wants to leave a message for the business.",
        whenCaller: "The caller asks to leave a message or have someone return the call.",
        exampleCallerPhrases: ["Please ask someone to call me back.", "Can I leave a message?"],
        priority: 30,
        appliesWhen: { timeMode: "any", locationIds: [], offeringIds: [], customCondition: null },
        actions: [{ type: "take_message", intakeFieldIds: ["field_name", "field_phone", "field_details"] }],
        collectFieldIds: ["field_name", "field_phone", "field_details"],
        requestTypeId: "request_general",
        notifyRecipientIds: [],
        fallback: { mode: "unknown_handling", instruction: null, routingRuleId: null },
        callerWording: "I can take a message and callback details for the team.",
      },
    ],
    routing: {
      enabled: false,
      contacts: [],
      teams: [],
      rules: [],
      defaults: { waitSeconds: 20, unansweredMode: "take_message_and_notify" },
    },
    followUps: [],
    unknownHandling: {
      enabled: true,
      askClarifyingQuestion: true,
      maximumClarificationAttempts: 1,
      defaultAction: "take_message",
      collectFieldIds: ["field_name", "field_phone", "field_details"],
      callerWording: "I do not have that information confirmed, but I can take your details and have the team follow up.",
      notifyRecipientIds: [],
      routingRuleId: null,
      createImprovementSuggestion: true,
      customInstruction: null,
    },
    spamScreening: {
      enabled: true,
      blockLikelyRobocalls: true,
      hideLikelySpamFromCalls: true,
      countBlockedTowardUsage: false,
      allowUnknownLocalNumbers: true,
      suspectedSpamAction: "screen",
    },
    greetingVoice: {
      enabled: true,
      openingGreeting: "Thanks for calling. How can I help today?",
      assistantName: "Answerley",
      voiceId: "voice-configurable",
      tone: "warm_helpful",
      customToneInstructions: null,
      primaryLanguage: "en",
      additionalLanguages: [],
      businessNamePronunciation: null,
      closingWording: "Thanks for calling. The team will follow up if needed.",
      voicePreviewText: "Thanks for calling. How can I help today?",
    },
    links: [],
    globalRules: {
      approvedKnowledgeOnly: true,
      doNotInventBusinessFacts: true,
      askOneQuestionAtATime: true,
      avoidRepeatingCollectedInformation: true,
      confirmBeforeCreatingRequest: true,
      pricingDefault: "use_offering_setting",
      conversationStyle: "natural",
      customInstructions: null,
    },
  };
}
