import { SBA_SCHEMA_VERSION, type AnsweringSetup } from "./schema";

const weekday = (open = true) => ({
  open,
  periods: open ? [{ opensAt: "09:00", closesAt: "17:00" }] : [],
  callerWording: open ? null : "We are closed today, but I can take a message.",
});

export const demoAnsweringSetup: AnsweringSetup = {
  schemaVersion: SBA_SCHEMA_VERSION,
  setupId: "setup_demo",
  businessId: "business_demo",
  brand: "Small Business Answering",
  status: {
    mode: "draft",
    draftRevision: 1,
    liveRevision: 0,
    isLive: false,
    isPaused: false,
    lastPublishedAt: null,
    lastTestedAt: "2026-06-24T15:00:00.000Z",
    needsReview: true,
  },
  business: {
    name: "Brightfield Services",
    websiteUrl: "https://example.com",
    publicPhone: "+1 204 555 0142",
    publicEmail: "hello@example.com",
    timezone: "America/Winnipeg",
    primaryLanguage: "en",
    additionalLanguages: [],
    pronunciation: "Bright-field Services",
    address: {
      line1: "100 Example Avenue",
      line2: null,
      city: "Winnipeg",
      region: "Manitoba",
      postalCode: "R3C 0A1",
      country: "Canada",
    },
    serviceArea: {
      summary: "We serve Winnipeg locally and offer remote consultations across Canada.",
      areas: ["Winnipeg", "Remote across Canada"],
    },
  },
  services: [
    {
      id: "service_consultation",
      enabled: true,
      name: "Introductory consultation",
      approvedDescription: "A first conversation to understand what the caller needs.",
      aliases: ["initial consultation", "first appointment"],
      canAnswerQuestions: true,
      canCaptureRequest: true,
      appointmentEligible: true,
      pricingWording: "Pricing is confirmed after the team reviews the request.",
    },
    {
      id: "service_support",
      enabled: true,
      name: "Customer support request",
      approvedDescription: "Help for existing customers who need a response from the team.",
      aliases: ["support", "existing customer help"],
      canAnswerQuestions: true,
      canCaptureRequest: true,
      appointmentEligible: false,
      pricingWording: null,
    },
  ],
  approvedAnswers: [
    {
      id: "answer_hours",
      question: "When are you open?",
      answer: "We are open Monday through Friday from 9 AM to 5 PM Central Time.",
      sourceIds: ["source_website"],
      needsReview: false,
    },
    {
      id: "answer_pricing",
      question: "How much does it cost?",
      answer: "Pricing is confirmed after the team reviews the request.",
      sourceIds: ["source_owner_edit"],
      needsReview: true,
    },
  ],
  hours: {
    timezone: "America/Winnipeg",
    regular: {
      monday: weekday(),
      tuesday: weekday(),
      wednesday: weekday(),
      thursday: weekday(),
      friday: weekday(),
      saturday: weekday(false),
      sunday: weekday(false),
    },
    temporaryUpdate: null,
    afterHours: {
      enabled: true,
      mode: "take_message",
      callerWording: "The team is unavailable right now, but I can take a message for them.",
      urgentWording: "If this is urgent, I can collect the details and alert the on-call contact.",
    },
  },
  callHandling: {
    mode: "overflow",
    answerTiming: {
      ringDelaySeconds: 30,
      answerWhenClosed: true,
      answerWhenBusy: true,
    },
    callerGreeting: "Thanks for calling Brightfield Services. How can I help today?",
    unknownAnswerBehavior: "take_message_and_flag",
  },
  requestCapture: {
    fields: ["caller_name", "phone", "reason", "service_needed", "preferred_time", "email"],
    callerSummaryWording: "I have captured your request and will send the details to the team.",
  },
  appointmentHandling: {
    mode: "capture_request",
    bookingLinkUrl: "https://example.com/book",
    calendarIntegration: "none",
    doNotCallBookedUntilConfirmed: true,
  },
  urgentRouting: {
    enabled: true,
    detectionPhrases: ["emergency", "urgent", "water leak", "no heat"],
    collectFields: ["caller_name", "phone", "address", "reason", "urgency"],
    transferEnabled: false,
    alertContactIds: ["contact_owner"],
  },
  ownerAlerts: {
    contacts: [
      {
        id: "contact_owner",
        role: "owner",
        name: "Primary owner",
        sms: null,
        email: "owner@example.com",
        enabled: true,
      },
    ],
    channels: ["email"],
    messageTemplate: "New call from {{caller_name}} about {{reason}}. Preferred time: {{preferred_time}}.",
  },
  callerConfirmations: {
    enabled: false,
    smsTemplate: null,
    sendBookingLinkWhenRelevant: true,
  },
  spamScreening: {
    enabled: true,
    keepOutOfBillableUsage: true,
    callerWording: "Thanks for calling. May I ask what this is regarding?",
  },
  privacy: {
    callRecording: "off",
    retentionDays: 30,
    callerDisclosure: "Calls may be summarized so the business can respond.",
  },
  sources: [
    {
      id: "source_website",
      type: "website",
      label: "Business website",
      url: "https://example.com",
      excerpt: "Brightfield Services helps customers with consultations and support.",
      capturedAt: "2026-06-24T12:00:00.000Z",
    },
    {
      id: "source_owner_edit",
      type: "owner_edit",
      label: "Owner edit",
      url: null,
      excerpt: "Pricing is confirmed after the team reviews the request.",
      capturedAt: "2026-06-24T15:00:00.000Z",
    },
  ],
  activationGates: [
    { id: "business_details", label: "Business details", status: "complete", description: "Confirm the business name, website, contact details, timezone, and service area." },
    { id: "services_answers", label: "Services and approved answers", status: "needs_review", description: "Review services, safe pricing wording, FAQs, and what the setup can answer." },
    { id: "hours_after_hours", label: "Hours and after-hours", status: "needs_review", description: "Confirm open hours, closed-day wording, and after-hours message handling." },
    { id: "greeting_voice", label: "Greeting and voice", status: "complete", description: "Approve the caller greeting, tone, language, and disclosure wording." },
    { id: "owner_alerts", label: "Owner alerts", status: "blocked", description: "Add an SMS number or email for owner alerts and urgent notifications." },
    { id: "phone_routing", label: "Phone routing", status: "blocked", description: "Choose forwarding, overflow, after-hours, or immediate answering before real callers hear it." },
    { id: "billing", label: "Billing", status: "blocked", description: "Add payment before live calls can be activated." },
    { id: "final_test", label: "Final test", status: "blocked", description: "Complete one approved test before publishing the setup for real callers." },
  ],
};
