export interface CapabilityContract {
  id: string;
  label: string;
  planPaths: string[];
  uiSurfaces: string[];
  assistantOperations: Array<"read" | "add" | "edit" | "disable" | "remove">;
  runtimeLayers: string[];
  operationalConsumers: string[];
  testIds: string[];
  status: "complete" | "partial" | "planned";
  note?: string;
}

export const capabilityContracts: CapabilityContract[] = [
  {
    id: "business-profile",
    label: "Business profile",
    planPaths: ["/businessProfile"],
    uiSurfaces: ["Confirm Basics", "Settings", "Plan Lab"],
    assistantOperations: ["read", "edit"],
    runtimeLayers: ["identity", "businessContext", "sessionRules"],
    operationalConsumers: ["Calls", "Requests", "Numbers"],
    testIds: ["schema-business-profile", "readiness-business-name"],
    status: "complete",
  },
  {
    id: "temporary-updates",
    label: "Temporary updates",
    planPaths: ["/temporaryUpdates"],
    uiSurfaces: ["Today’s Update", "Plan Lab"],
    assistantOperations: ["read", "add", "edit", "disable", "remove"],
    runtimeLayers: ["businessContext"],
    operationalConsumers: ["Calls"],
    testIds: ["schema-temporary-update"],
    status: "complete",
  },
  {
    id: "offerings",
    label: "Offerings",
    planPaths: ["/offerings"],
    uiSurfaces: ["What You Offer", "Plan Lab", "Test suggestions"],
    assistantOperations: ["read", "add", "edit", "disable", "remove"],
    runtimeLayers: ["businessContext", "workflowRules"],
    operationalConsumers: ["Calls", "Requests"],
    testIds: ["schema-offerings", "readiness-pricing"],
    status: "complete",
  },
  {
    id: "pricing-behavior",
    label: "Pricing behavior",
    planPaths: ["/offerings/*/pricing"],
    uiSurfaces: ["What You Offer", "Critical review", "Plan Lab"],
    assistantOperations: ["read", "edit"],
    runtimeLayers: ["groundingRules", "businessContext"],
    operationalConsumers: ["Calls"],
    testIds: ["readiness-pricing"],
    status: "complete",
  },
  {
    id: "hours-availability",
    label: "Hours and availability",
    planPaths: ["/hoursAvailability"],
    uiSurfaces: ["Hours & Availability", "Confirm Basics", "Plan Lab"],
    assistantOperations: ["read", "edit"],
    runtimeLayers: ["businessContext", "workflowRules", "sessionRules"],
    operationalConsumers: ["Calls", "Routing", "Messages"],
    testIds: ["readiness-timezone"],
    status: "complete",
  },
  {
    id: "locations-coverage",
    label: "Locations and coverage",
    planPaths: ["/locationsCoverage"],
    uiSurfaces: ["Locations & Coverage", "Confirm Basics", "Plan Lab"],
    assistantOperations: ["read", "add", "edit", "disable", "remove"],
    runtimeLayers: ["businessContext", "workflowRules"],
    operationalConsumers: ["Calls", "Requests", "Routing"],
    testIds: ["schema-coverage"],
    status: "complete",
  },
  {
    id: "knowledge",
    label: "FAQs and policies",
    planPaths: ["/knowledgeItems"],
    uiSurfaces: ["FAQs & Policies", "Unknown-answer update", "Plan Lab"],
    assistantOperations: ["read", "add", "edit", "disable", "remove"],
    runtimeLayers: ["groundingRules", "businessContext"],
    operationalConsumers: ["Calls", "Unknown questions"],
    testIds: ["schema-knowledge"],
    status: "complete",
  },
  {
    id: "request-types",
    label: "Request types",
    planPaths: ["/requestTypes"],
    uiSurfaces: ["Bookings & Intake", "Requests", "Plan Lab"],
    assistantOperations: ["read", "add", "edit", "disable", "remove"],
    runtimeLayers: ["workflowRules", "toolPolicy"],
    operationalConsumers: ["Requests", "Call Detail"],
    testIds: ["readiness-request-fields"],
    status: "complete",
  },
  {
    id: "intake-fields",
    label: "Custom intake fields",
    planPaths: ["/intakeFields"],
    uiSurfaces: ["Bookings & Intake", "Scenario editor", "Plan Lab"],
    assistantOperations: ["read", "add", "edit", "disable", "remove"],
    runtimeLayers: ["conversationRules", "workflowRules", "toolPolicy"],
    operationalConsumers: ["Calls", "Requests", "Messages"],
    testIds: ["readiness-request-fields"],
    status: "complete",
  },
  {
    id: "booking",
    label: "Booking behavior",
    planPaths: ["/booking"],
    uiSurfaces: ["Bookings & Intake", "Critical review", "Plan Lab"],
    assistantOperations: ["read", "edit", "disable"],
    runtimeLayers: ["workflowRules", "toolPolicy"],
    operationalConsumers: ["Requests", "Messages", "Integrations"],
    testIds: ["readiness-booking-link", "readiness-booking-integration"],
    status: "complete",
  },
  {
    id: "scenarios",
    label: "Call scenarios",
    planPaths: ["/scenarios"],
    uiSurfaces: ["Common Call Scenarios", "Plan Lab"],
    assistantOperations: ["read", "add", "edit", "disable", "remove"],
    runtimeLayers: ["workflowRules", "toolPolicy"],
    operationalConsumers: ["Calls", "Requests", "Messages", "Routing"],
    testIds: ["readiness-scenario-references"],
    status: "complete",
  },
  {
    id: "routing-contacts",
    label: "Routing contacts and teams",
    planPaths: ["/routing/contacts", "/routing/teams"],
    uiSurfaces: ["Routing & Escalation", "Critical review", "Plan Lab"],
    assistantOperations: ["read", "add", "edit", "disable", "remove"],
    runtimeLayers: ["workflowRules", "toolPolicy"],
    operationalConsumers: ["Calls", "Messages", "Transfers"],
    testIds: ["readiness-transfer-contact", "readiness-notification-contact"],
    status: "complete",
  },
  {
    id: "routing-rules",
    label: "Routing and escalation rules",
    planPaths: ["/routing/rules"],
    uiSurfaces: ["Routing & Escalation", "Plan Lab"],
    assistantOperations: ["read", "add", "edit", "disable", "remove"],
    runtimeLayers: ["workflowRules", "toolPolicy"],
    operationalConsumers: ["Calls", "Call Events", "Transfers"],
    testIds: ["readiness-transfer-contact"],
    status: "complete",
  },
  {
    id: "follow-ups",
    label: "Follow-ups and alerts",
    planPaths: ["/followUps"],
    uiSurfaces: ["Follow-up & Messages", "Messages", "Plan Lab"],
    assistantOperations: ["read", "add", "edit", "disable", "remove"],
    runtimeLayers: ["workflowRules", "toolPolicy"],
    operationalConsumers: ["Messages", "Call Events", "Usage"],
    testIds: ["readiness-followup-link", "readiness-notification-phone"],
    status: "complete",
  },
  {
    id: "unknown-handling",
    label: "Unknown-question handling",
    planPaths: ["/unknownHandling"],
    uiSurfaces: ["Test page update card", "Critical review", "Plan Lab"],
    assistantOperations: ["read", "edit"],
    runtimeLayers: ["groundingRules", "workflowRules", "toolPolicy"],
    operationalConsumers: ["Calls", "Unknown questions", "Plan improvements"],
    testIds: ["readiness-unknown-handling"],
    status: "complete",
  },
  {
    id: "spam-screening",
    label: "Spam screening",
    planPaths: ["/spamScreening"],
    uiSurfaces: ["Spam Screening", "Spam", "Plan Lab"],
    assistantOperations: ["read", "edit", "disable"],
    runtimeLayers: ["modeRules"],
    operationalConsumers: ["Calls", "Usage"],
    testIds: ["schema-spam"],
    status: "complete",
  },
  {
    id: "greeting-voice",
    label: "Greeting and voice",
    planPaths: ["/greetingVoice"],
    uiSurfaces: ["Greeting & Voice", "Test call", "Plan Lab"],
    assistantOperations: ["read", "edit", "disable"],
    runtimeLayers: ["identity", "voiceAndSpeakingStyle", "conversationRules"],
    operationalConsumers: ["Calls"],
    testIds: ["readiness-greeting"],
    status: "complete",
  },
  {
    id: "links",
    label: "Reusable links",
    planPaths: ["/links"],
    uiSurfaces: ["Offerings", "Knowledge", "Booking", "Follow-ups", "Plan Lab"],
    assistantOperations: ["read", "add", "edit", "disable", "remove"],
    runtimeLayers: ["businessContext", "toolPolicy"],
    operationalConsumers: ["Messages", "Requests"],
    testIds: ["readiness-link-references"],
    status: "complete",
  },
  {
    id: "metadata",
    label: "Source and confirmation metadata",
    planPaths: ["fieldMetadata"],
    uiSurfaces: ["Found on website", "Needs confirmation", "Conflict", "Plan Lab"],
    assistantOperations: ["read", "edit"],
    runtimeLayers: [],
    operationalConsumers: ["Scrape review", "Audit history"],
    testIds: ["metadata-update"],
    status: "complete",
  },
  {
    id: "versions",
    label: "Plan revisions and snapshots",
    planPaths: ["revision", "publishedRevision"],
    uiSurfaces: ["Revision badge", "Audit history", "Call Detail"],
    assistantOperations: [],
    runtimeLayers: ["sessionRules"],
    operationalConsumers: ["Calls", "Requests", "Runtime Compilations"],
    testIds: ["patch-revision-conflict"],
    status: "complete",
  },
  {
    id: "plan-integrity",
    label: "Plan integrity and patch guardrails",
    planPaths: ["all cross-references", "all patch targets"],
    uiSurfaces: ["Plan Lab", "Contract Health", "Change preview"],
    assistantOperations: ["read", "add", "edit", "disable", "remove"],
    runtimeLayers: ["all enabled references"],
    operationalConsumers: ["Plan versions", "Audit history"],
    testIds: ["integrity-references", "patch-root-guardrail", "patch-revision-conflict"],
    status: "complete",
  },
  {
    id: "guest-handoff",
    label: "Guest setup and account handoff",
    planPaths: ["guest plan envelope", "guest test activity"],
    uiSurfaces: ["Customer slice", "Save setup", "Calls dashboard"],
    assistantOperations: [],
    runtimeLayers: ["test runtime"],
    operationalConsumers: ["Guest Session", "Business", "Plan Version", "Test Call"],
    testIds: ["guest-session-contract"],
    status: "complete",
    note: "Persistence contract and database model are established; provider wiring is a later visible slice.",
  },
  {
    id: "improvements-audit",
    label: "Improvement suggestions and audit",
    planPaths: ["/unknownHandling/createImprovementSuggestion", "plan changes"],
    uiSurfaces: ["Unknown-answer card", "Call Detail", "Audit history"],
    assistantOperations: ["read", "edit"],
    runtimeLayers: ["unknown handling", "tool policy"],
    operationalConsumers: ["Plan Improvement Suggestions", "Audit Events"],
    testIds: ["operations-improvement-audit"],
    status: "complete",
  },
  {
    id: "provider-boundaries",
    label: "Provider integration boundaries",
    planPaths: ["connection references", "runtime tools"],
    uiSurfaces: ["Test call", "Numbers", "Billing", "Integrations"],
    assistantOperations: [],
    runtimeLayers: ["tool policy", "mode rules"],
    operationalConsumers: ["Voice Gateway", "Messaging", "Numbers", "Booking", "Billing"],
    testIds: ["provider-contracts"],
    status: "complete",
  },
  {
    id: "runtime-compiler",
    label: "Gemini Live runtime compilation",
    planPaths: ["all enabled plan sections"],
    uiSurfaces: ["Runtime preview", "Contract Health"],
    assistantOperations: [],
    runtimeLayers: ["all"],
    operationalConsumers: ["Browser test", "Live calls"],
    testIds: ["runtime-coverage"],
    status: "complete",
  },
];

export function contractHealthSummary() {
  const complete = capabilityContracts.filter((item) => item.status === "complete").length;
  const partial = capabilityContracts.filter((item) => item.status === "partial").length;
  const planned = capabilityContracts.filter((item) => item.status === "planned").length;
  return {
    total: capabilityContracts.length,
    complete,
    partial,
    planned,
    healthy: partial === 0 && planned === 0,
  };
}
