import type { AnsweringPlanEnvelope } from "./schema";

const weekday = (open = true) => ({
  open,
  periods: open ? [{ opensAt: "09:00", closesAt: "17:00" }] : [],
  note: null,
});

export const genericAnsweringPlanFixture: AnsweringPlanEnvelope = {
  id: "plan_demo",
  businessId: "business_demo",
  revision: 7,
  publishedRevision: 6,
  createdAt: "2026-06-24T12:00:00.000Z",
  updatedAt: "2026-06-24T15:00:00.000Z",
  document: {
    schemaVersion: "1.0.0",
    businessProfile: {
      businessName: "Brightfield Services",
      legalName: null,
      websiteUrl: "https://example.com",
      businessType: {
        label: "Service business",
        description: "A business that answers questions and accepts customer requests.",
        aliases: ["local service company"],
      },
      description:
        "Brightfield Services helps customers with consultations, project requests, and ongoing support.",
      timezone: "America/Winnipeg",
      primaryLanguage: "en",
      additionalLanguages: [],
      publicContact: {
        phone: "+1 204 555 0142",
        email: "hello@example.com",
        contactUrl: "https://example.com/contact",
      },
      address: {
        line1: "100 Example Avenue",
        line2: null,
        city: "Winnipeg",
        region: "Manitoba",
        postalCode: "R3C 0A1",
        country: "Canada",
      },
      businessNamePronunciation: "Bright-field Services",
    },
    temporaryUpdates: [
      {
        id: "update_1",
        enabled: false,
        title: "Temporary business update",
        message: "We are operating with limited availability today.",
        mentionWhen: "when_relevant",
        startsAt: null,
        expiresAt: null,
        removeAutomatically: true,
      },
    ],
    offerings: [
      {
        id: "offering_consultation",
        enabled: true,
        name: "Introductory consultation",
        title: "Introductory consultation",
        description: "A first conversation to understand what the caller needs.",
        aliases: ["initial consultation", "first appointment"],
        canAnswerQuestions: true,
        requestable: true,
        bookable: true,
        canSendBookingLink: true,
        pricing: {
          mode: "do_not_quote",
          currency: "CAD",
          startingPrice: null,
          minimumPrice: null,
          maximumPrice: null,
          fixedPrice: null,
          approvedWording: "Pricing is confirmed after the team reviews the request.",
        },
        requestTypeId: "request_consultation",
        intakeFieldIds: ["field_name", "field_phone", "field_email", "field_preferred_time", "field_details"],
        locationIds: [],
        linkIds: ["link_booking"],
        additionalInstructions: null,
      },
      {
        id: "offering_support",
        enabled: true,
        name: "Customer support request",
        title: "Customer support",
        description: "Help for existing customers who need a response from the team.",
        aliases: ["support", "existing customer help"],
        canAnswerQuestions: true,
        requestable: true,
        bookable: false,
        canSendBookingLink: false,
        pricing: {
          mode: "do_not_quote",
          currency: "CAD",
          startingPrice: null,
          minimumPrice: null,
          maximumPrice: null,
          fixedPrice: null,
          approvedWording: null,
        },
        requestTypeId: "request_callback",
        intakeFieldIds: ["field_name", "field_phone", "field_details"],
        locationIds: [],
        linkIds: ["link_contact"],
        additionalInstructions: "Do not ask the caller to repeat details already collected.",
      },
    ],
    hoursAvailability: {
      enabled: true,
      timezone: "America/Winnipeg",
      regularHours: {
        monday: weekday(),
        tuesday: weekday(),
        wednesday: weekday(),
        thursday: weekday(),
        friday: weekday(),
        saturday: weekday(false),
        sunday: weekday(false),
      },
      specialDates: [],
      afterHours: {
        enabled: true,
        mode: "take_message",
        instructions: "Collect the caller's details and reason for calling.",
        callerWording: "The team is unavailable right now, but I can take a message for them.",
        routingRuleId: null,
      },
      availabilityNotes: "Specific appointment availability is confirmed by the team.",
    },
    locationsCoverage: {
      enabled: true,
      mode: "hybrid",
      locations: [
        {
          id: "location_main",
          enabled: true,
          name: "Main office",
          description: "Primary business location.",
          address: {
            line1: "100 Example Avenue",
            line2: null,
            city: "Winnipeg",
            region: "Manitoba",
            postalCode: "R3C 0A1",
            country: "Canada",
          },
          phone: "+1 204 555 0142",
          email: "hello@example.com",
          hoursOverride: null,
          offeringIds: ["offering_consultation", "offering_support"],
          bookingLinkId: "link_booking",
          routingRuleId: null,
        },
      ],
      serviceAreas: [
        {
          id: "coverage_remote",
          enabled: true,
          type: "custom",
          label: "Remote availability",
          value: "Remote consultations are available across Canada.",
          excluded: false,
        },
      ],
      callerFacingDescription: "We serve Winnipeg locally and offer remote consultations across Canada.",
    },
    knowledgeItems: [
      {
        id: "knowledge_hours",
        enabled: true,
        type: "faq",
        title: "Business hours",
        question: "When are you open?",
        alternativeQuestions: ["What are your hours?", "Are you open today?"],
        answer: "The business is open Monday through Friday from 9 AM to 5 PM Central Time.",
        behavior: {
          mode: "answer_directly",
          linkId: null,
          routingRuleId: null,
        },
        appliesTo: { offeringIds: [], locationIds: [] },
        internalNotes: null,
      },
      {
        id: "knowledge_cancellation",
        enabled: true,
        type: "policy",
        title: "Cancellation policy",
        question: "What is your cancellation policy?",
        alternativeQuestions: ["Can I cancel my appointment?"],
        answer: "Please contact the team as soon as possible if you need to change or cancel a request.",
        behavior: {
          mode: "answer_and_send_link",
          linkId: "link_contact",
          routingRuleId: null,
        },
        appliesTo: { offeringIds: [], locationIds: [] },
        internalNotes: null,
      },
    ],
    requestTypes: [
      {
        id: "request_consultation",
        enabled: true,
        name: "Consultation request",
        singularLabel: "Consultation",
        pluralLabel: "Consultations",
        description: "A request to arrange an introductory consultation.",
        intakeFieldIds: ["field_name", "field_phone", "field_email", "field_preferred_time", "field_details"],
        completionMode: "create_request",
        defaultAssigneeContactIds: ["contact_primary"],
        confirmationWording: "I have captured your consultation request for the team.",
        statuses: ["requested", "confirmed", "completed"],
      },
      {
        id: "request_callback",
        enabled: true,
        name: "Callback request",
        singularLabel: "Callback",
        pluralLabel: "Callbacks",
        description: "A request for someone from the business to return the call.",
        intakeFieldIds: ["field_name", "field_phone", "field_details"],
        completionMode: "create_request",
        defaultAssigneeContactIds: ["contact_primary"],
        confirmationWording: "I have your message and callback details ready for the team.",
        statuses: ["requested", "completed"],
      },
    ],
    intakeFields: [
      {
        id: "field_name",
        enabled: true,
        label: "Name",
        key: "name",
        type: "text",
        required: true,
        options: [],
        spokenPrompt: "May I have your name?",
        validationInstructions: null,
        askWhen: { mode: "always", requestTypeIds: [], offeringIds: [], scenarioIds: [], customCondition: null },
        order: 1,
      },
      {
        id: "field_phone",
        enabled: true,
        label: "Phone",
        key: "phone",
        type: "phone",
        required: true,
        options: [],
        spokenPrompt: "What is the best phone number to reach you?",
        validationInstructions: "Read the number back once for confirmation.",
        askWhen: { mode: "always", requestTypeIds: [], offeringIds: [], scenarioIds: [], customCondition: null },
        order: 2,
      },
      {
        id: "field_email",
        enabled: true,
        label: "Email",
        key: "email",
        type: "email",
        required: false,
        options: [],
        spokenPrompt: "What email address should the team use?",
        validationInstructions: null,
        askWhen: { mode: "request_type", requestTypeIds: ["request_consultation"], offeringIds: [], scenarioIds: [], customCondition: null },
        order: 3,
      },
      {
        id: "field_preferred_time",
        enabled: true,
        label: "Preferred date or time",
        key: "preferred_time",
        type: "text",
        required: false,
        options: [],
        spokenPrompt: "What day or time works best for you?",
        validationInstructions: "Treat this as a preference, not a confirmed booking.",
        askWhen: { mode: "request_type", requestTypeIds: ["request_consultation"], offeringIds: [], scenarioIds: [], customCondition: null },
        order: 4,
      },
      {
        id: "field_details",
        enabled: true,
        label: "Reason for calling",
        key: "details",
        type: "multiline_text",
        required: true,
        options: [],
        spokenPrompt: "What would you like the team to know?",
        validationInstructions: null,
        askWhen: { mode: "always", requestTypeIds: [], offeringIds: [], scenarioIds: [], customCondition: null },
        order: 5,
      },
    ],
    booking: {
      enabled: true,
      defaultMethod: "send_link",
      bookingLinkId: "link_booking",
      integrationConnectionId: null,
      defaultIntakeFieldIds: ["field_name", "field_phone", "field_email", "field_preferred_time"],
      confirmationWording: "I can send the booking link and capture your preferred time for the team.",
      unavailableBehavior: {
        mode: "collect_preferred_time",
        wording: "I can take your preferred time and have the team confirm it.",
      },
      offeringOverrides: [],
    },
    scenarios: [
      {
        id: "scenario_information",
        enabled: true,
        name: "Business information question",
        description: "A caller asks about approved business information.",
        whenCaller: "The caller asks about offerings, hours, location, coverage, or an approved FAQ or policy.",
        exampleCallerPhrases: ["What do you offer?", "Are you open on Friday?"],
        priority: 10,
        appliesWhen: { timeMode: "any", locationIds: [], offeringIds: [], customCondition: null },
        actions: [{ type: "answer_approved_information", knowledgeItemIds: [] }],
        collectFieldIds: [],
        requestTypeId: null,
        notifyRecipientIds: [],
        fallback: { mode: "unknown_handling", instruction: null, routingRuleId: null },
        callerWording: null,
      },
      {
        id: "scenario_booking",
        enabled: true,
        name: "Consultation or booking request",
        description: "A caller wants to request a consultation or preferred time.",
        whenCaller: "The caller wants an appointment, consultation, booking, or callback.",
        exampleCallerPhrases: ["I would like to book a consultation.", "Can someone call me back?"],
        priority: 20,
        appliesWhen: { timeMode: "any", locationIds: [], offeringIds: [], customCondition: null },
        actions: [
          { type: "collect_information", intakeFieldIds: ["field_name", "field_phone", "field_preferred_time", "field_details"] },
          { type: "create_request", requestTypeId: "request_consultation" },
          { type: "prepare_follow_up", followUpId: "followup_booking_link" },
        ],
        collectFieldIds: ["field_name", "field_phone", "field_preferred_time", "field_details"],
        requestTypeId: "request_consultation",
        notifyRecipientIds: ["contact_primary"],
        fallback: { mode: "take_message", instruction: null, routingRuleId: null },
        callerWording: "I can help capture your request and preferred time.",
      },
      {
        id: "scenario_message",
        enabled: true,
        name: "Message or callback request",
        description: "A caller wants to leave a message for the business.",
        whenCaller: "The caller asks to leave a message or have someone return the call.",
        exampleCallerPhrases: ["Please ask someone to call me back.", "Can I leave a message?"],
        priority: 30,
        appliesWhen: { timeMode: "any", locationIds: [], offeringIds: [], customCondition: null },
        actions: [
          { type: "take_message", intakeFieldIds: ["field_name", "field_phone", "field_details"] },
          { type: "notify", recipientIds: ["contact_primary"] },
        ],
        collectFieldIds: ["field_name", "field_phone", "field_details"],
        requestTypeId: "request_callback",
        notifyRecipientIds: ["contact_primary"],
        fallback: { mode: "unknown_handling", instruction: null, routingRuleId: null },
        callerWording: "I can take a message and callback details for the team.",
      },
    ],
    routing: {
      enabled: true,
      contacts: [
        {
          id: "contact_primary",
          enabled: true,
          name: "Primary business contact",
          roleLabel: "Owner or office contact",
          phone: null,
          email: "hello@example.com",
          availabilityNote: null,
          notificationPreferences: { sms: true, email: true, call: true },
        },
      ],
      teams: [
        {
          id: "team_main",
          enabled: true,
          name: "Main team",
          description: "The default business team.",
          contactIds: ["contact_primary"],
        },
      ],
      rules: [
        {
          id: "routing_important",
          enabled: false,
          name: "Important calls",
          appliesWhen: {
            scenarioIds: [],
            requestTypeIds: [],
            locationIds: [],
            timeMode: "any",
            customCondition: "The caller explicitly asks to speak with a person and the business permits transfer.",
          },
          duringBusinessHours: { action: "transfer", recipientIds: ["contact_primary"], instruction: null },
          afterHours: { action: "take_message_and_notify", recipientIds: ["contact_primary"], instruction: null },
          transferSequence: [{ recipientId: "contact_primary", waitSeconds: 20 }],
          ifUnanswered: { action: "take_message_and_notify", recipientIds: ["contact_primary"], instruction: null },
          notifyRecipientIds: ["contact_primary"],
          callerWording: "Let me try the team. If no one is available, I can take a message.",
        },
      ],
      defaults: { waitSeconds: 20, unansweredMode: "take_message_and_notify" },
    },
    followUps: [
      {
        id: "followup_booking_link",
        enabled: true,
        name: "Booking link requested",
        trigger: "booking_link_requested",
        scenarioIds: ["scenario_booking"],
        channel: "sms",
        recipientType: "caller",
        recipientIds: [],
        messageText: "Here is the link to continue your booking request: {{booking_link}}",
        includeLink: true,
        linkId: "link_booking",
        notifyOwner: false,
        sendingWindow: { mode: "anytime", customRule: null },
      },
      {
        id: "followup_owner_alert",
        enabled: true,
        name: "New request alert",
        trigger: "request_captured",
        scenarioIds: ["scenario_booking", "scenario_message"],
        channel: "sms",
        recipientType: "contact",
        recipientIds: ["contact_primary"],
        messageText: "A new caller request was captured. Open Answerley to review the details.",
        includeLink: false,
        linkId: null,
        notifyOwner: true,
        sendingWindow: { mode: "anytime", customRule: null },
      },
    ],
    unknownHandling: {
      enabled: true,
      askClarifyingQuestion: true,
      maximumClarificationAttempts: 1,
      defaultAction: "take_message",
      collectFieldIds: ["field_name", "field_phone", "field_details"],
      callerWording: "I do not have that information confirmed, but I can take your details and have the team follow up.",
      notifyRecipientIds: ["contact_primary"],
      routingRuleId: null,
      createImprovementSuggestion: true,
      customInstruction: null,
    },
    spamScreening: {
      enabled: true,
      blockLikelyRobocalls: true,
      hideLikelySpamFromCalls: true,
      countBlockedTowardUsage: false,
      allowUnknownLocalNumbers: true,
      suspectedSpamAction: "screen",
    },
    greetingVoice: {
      enabled: true,
      openingGreeting: "Thanks for calling Brightfield Services. How can I help today?",
      assistantName: "Answerley",
      voiceId: "voice-configurable",
      tone: "warm_helpful",
      customToneInstructions: null,
      primaryLanguage: "en",
      additionalLanguages: [],
      businessNamePronunciation: "Bright-field Services",
      closingWording: "Thanks for calling. The team will follow up if needed.",
      voicePreviewText: "Thanks for calling Brightfield Services. How can I help today?",
    },
    links: [
      {
        id: "link_booking",
        enabled: true,
        label: "Booking page",
        type: "booking",
        url: "https://example.com/book",
        description: "Used when a caller asks to continue a booking request.",
      },
      {
        id: "link_contact",
        enabled: true,
        label: "Contact page",
        type: "contact",
        url: "https://example.com/contact",
        description: "General business contact page.",
      },
    ],
    globalRules: {
      approvedKnowledgeOnly: true,
      doNotInventBusinessFacts: true,
      askOneQuestionAtATime: true,
      avoidRepeatingCollectedInformation: true,
      confirmBeforeCreatingRequest: true,
      pricingDefault: "use_offering_setting",
      conversationStyle: "natural",
      customInstructions: null,
    },
  },
  fieldMetadata: {
    "/businessProfile/businessName": {
      sourceType: "website",
      sources: [
        {
          sourceType: "website",
          sourceDocumentId: "source_home",
          sourceUrl: "https://example.com",
          sourceLabel: "Homepage",
          excerpt: "Brightfield Services",
          observedAt: "2026-06-24T14:45:00.000Z",
        },
      ],
      confidence: 0.99,
      confirmedByUser: false,
      confirmedAt: null,
      lastChangedBy: "website_builder",
      lastChangedAt: "2026-06-24T14:45:00.000Z",
      conflicts: [],
      note: null,
    },
    "/businessProfile/timezone": {
      sourceType: "assistant",
      sources: [],
      confidence: 0.73,
      confirmedByUser: false,
      confirmedAt: null,
      lastChangedBy: "website_builder",
      lastChangedAt: "2026-06-24T14:45:00.000Z",
      conflicts: [],
      note: "Inferred from the business location.",
    },
    "/routing/contacts/0/phone": {
      sourceType: "system",
      sources: [],
      confidence: null,
      confirmedByUser: false,
      confirmedAt: null,
      lastChangedBy: "system",
      lastChangedAt: "2026-06-24T14:45:00.000Z",
      conflicts: [],
      note: "Needed only when SMS alerts or call transfers are enabled.",
    },
  },
};

export const cloneFixturePlan = (): AnsweringPlanEnvelope =>
  structuredClone(genericAnsweringPlanFixture);
